# Generated by Django 3.0.7 on 2020-06-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('orden_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(),
        ),
    ]
