# Generated by Django 3.0.7 on 2020-06-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0002_auto_20200611_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
