# Generated by Django 3.0.7 on 2020-06-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0005_auto_20200612_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
