# Generated by Django 3.0.7 on 2020-06-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0009_auto_20200613_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='carro',
            name='producto_id',
            field=models.ManyToManyField(to='Trades.producto'),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_id',
            field=models.ManyToManyField(to='Trades.producto'),
        ),
    ]
