# Generated by Django 3.0.7 on 2020-06-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0010_auto_20200613_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='carro',
            name='producto_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carro',
            name='usuario_id',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_id',
            field=models.IntegerField(default=1),
        ),
    ]
