# Generated by Django 3.0.7 on 2020-06-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0011_auto_20200613_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario_id',
            field=models.IntegerField(default=1),
        ),
    ]
